### PR TITLE
readding npm-run-all

### PR DESCRIPTION
**Pull request by kazekagegaara**
Readding with latest version on npm-run-all

### CODE REVIEW

**Comment by kentcdodds** [comment]
Looks awesome. Thanks! @nyrosmith could you verify this works on your machine before we merge it? Feel free to merge it if it does :+1

**Comment by nyrosmith** [comment]
Will check right after breakfast

**Comment by nyrosmith** [comment]
Looks good. Thx @kazekagegaara

**Comment by kentcdodds** [comment]
Thanks @kazekagegaara. You've been given commit access. Please continue to make contributions via PRs rather than committing directly to master. Thanks!

**Comment by sarbbottam** [comment]
:loudspeaker: you could use [`serial` instead of `sequential`](https://github.com/mysticatea/npm-run-all/pull/31) if you would prefer.

**Comment by kentcdodds** [comment]
Nice! I get it confused a lot! :D

**Pull request merged**
